url: "http://www.spdk.io"
baseurl: ""
title: Storage Performance Development Kit
email: benjamin.walker@intel.com
author: Benjamin Walker
description: >
  The Storage Performance Development Kit (SPDK) provides a set of tools and libraries
  for writing high performance, scalable, user-mode storage applications.
  It achieves high performance by moving all of the necessary drivers into userspace
  and operating in a polled mode instead of relying on interrupts,
  which avoids kernel context switches and eliminates interrupt handling overhead.
copyright: 'Copyright &copy; Intel Corporation. All Rights Reserved.'
markdown: kramdown
permalink: pretty

boxes:
  - title: home
    url: http://www.spdk.io/
    ico: home
  - title: download
    url: http://www.spdk.io/releases/
    ico: download-alt
  - title: documentation
    url: http://www.spdk.io/doc/
    ico: book
  - title: development
    url: http://www.spdk.io/development/
    ico: wrench
  - title: mailing list
    url: https://lists.01.org/mailman/listinfo/spdk
    ico: envelope
  - title: Blog
    url: http://www.spdk.io/blog/
    ico: comment


gems:
  - jekyll-feed
