url: "https://spdk.github.io"
baseurl: "http://www.spdk.io"
title: Storage Performance Development Kit
email: benjamin.walker@intel.com
author: Benjamin Walker
description: >
  The Storage Performance Development Kit (SPDK) provides a set of tools and libraries
  for writing high performance, scalable, user-mode storage applications.
  It achieves high performance by moving all of the necessary drivers into userspace
  and operating in a polled mode instead of relying on interrupts,
  which avoids kernel context switches and eliminates interrupt handling overhead.
copyright: 'Copyright &copy; Intel Corporation. All Rights Reserved.'
markdown: kramdown
permalink: pretty

boxes:
  - title: github
    url: https://github.com/spdk/spdk
    ico: img/ico/github.png
  - title: mailing list
    url: https://lists.01.org/mailman/listinfo/spdk
    ico: img/ico/125a-email-message-solid.svg
  - title: documentation
    url: http://spdk.io/spdk/doc/
    ico: img/ico/003-instructions.svg

gems:
  - jekyll-feed
